[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = ['cd server && npm install --production']

[phases.build]
cmds = ['echo "No build step required"']

[variables]
PORT = "8080"

[start]
[start]
cmd = "cd server && node server-production.js"