#!/bin/bash

# Railway Environment Variables Fix Script
# This script helps set up the correct environment variables for KingChat

echo "🔧 Railway Environment Variables Setup"
echo "======================================="

echo ""
echo "📋 Required Environment Variables:"
echo ""
echo "1. DATABASE_URL:"
echo "   postgresql://postgres:uEDCzaMjeCGBXCItjOqqMNEYECEFgBsn@postgres.railway.internal:5432/railway"
echo ""
echo "2. JWT_SECRET:"
echo "   railway-jwt-secret-2024"
echo ""
echo "3. NODE_ENV:"
echo "   production"
echo ""
echo "4. PORT:"
echo "   8080"
echo ""
echo "🚀 Steps to fix in Railway Dashboard:"
echo ""
echo "1. Go to: https://railway.app/dashboard"
echo "2. Select your KingChat project"
echo "3. Click on 'Variables' tab"
echo "4. Add/Update these variables:"
echo ""
echo "   Variable Name: DATABASE_URL"
echo "   Value: postgresql://postgres:uEDCzaMjeCGBXCItjOqqMNEYECEFgBsn@postgres.railway.internal:5432/railway"
echo ""
echo "   Variable Name: JWT_SECRET" 
echo "   Value: railway-jwt-secret-2024"
echo ""
echo "   Variable Name: NODE_ENV"
echo "   Value: production"
echo ""
echo "   Variable Name: PORT"
echo "   Value: 8080"
echo ""
echo "5. Click 'Deploy' to redeploy with new variables"
echo ""
echo "✅ After setting variables, your deployment should work correctly!"
echo ""
echo "🔍 You can verify by checking the logs for:"
echo "   - NODE_ENV: production"
echo "   - DATABASE_URL: SET"
echo "   - JWT_SECRET: SET"
echo "   - Database connection: successful"